var requirejs=requirejs||require;require(["require","require.config.core"],function(b,g){requirejs.config(g);b(["config","browser"],function(){b("browser").ready(function(){})})});define("boot",function(){});define("local_config",[],function(){return{env:"prod",browser:"chrome"}});
define("app_config",[],function(){return{remote_src:{dev:"https://s3.amazonaws.com/stage.static.surf.bittorrent.com/remotejs/",stage:"https://s3.amazonaws.com/stage.static.surf.bittorrent.com/remotejs/",prod:"https://s3.amazonaws.com/static.surf.bittorrent.com/remotejs/"},btfc_url:{dev:"http://stage.surf.bittorrent.com",stage:"http://stage.surf.bittorrent.com",prod:"http://surf.bittorrent.com"},TBS:1,TBV:1,TBN:3,GA:"UA-36492394-1",notifications:{SARCH_START:"search_start",SEARCH_COMPLETE:"search_complete",
SCRAPE_COMPLETE:"scrape_complete",DOWNLOAD_COMPLETE:"download_complete",DOWNLOAD_FAILED:"download_failed",DOWNLOAD_STARTED:"download_started",SEARCH_SITE_ADDED:"search_site_added",SEARCH_SITE_DECLINED:"search_site_declined",ATTEMPT_ADD_SITE:"attempt_add_site",SEARCH_SITE_ADD_FAIL:"search_site_add_fail",SEARCH_SITE_DISCOVERED:"search_site_discovered",AUTHORIZE_PAIRING:"pairing_requested",CLIENT_AUTHORIZED:"client_authorized",CLIP:"clip"},settings_defaults:{seed_type:"percentage",seed_time:10,seed_percentage:200,
default_engine:"isohunt.com",associate:null,remember_association:null,first_run:!0}}});
define("config",["require","local_config","app_config"],function(b){var g={browser:"undefined"===typeof Cc&&"undefined"===typeof addon&&!("undefined"!==typeof document&&"MozBoxSizing"in document.documentElement.style)?"undefined"===typeof chrome?"safari":"chrome":"firefox",env:"prod",source:null},h=b("app_config"),a;try{a=b("local_config")}catch(f){}if(void 0!==a)for(var k in a)g[k]=a[k];g.app=h;g.is_chrome=function(){return"chrome"===g.browser};g.is_ff=function(){return"firefox"===g.browser};g.is_safari=
function(){return"safari"===g.browser};g.data_path=g.data_path||"undefined"!==typeof BT_BUILD_SCRIPT?"/":g.is_safari()?safari.extension.baseURI:g.is_chrome()?"undefined"!==typeof chrome&&chrome.extension?chrome.extension.getURL(""):"/":self&&self.data?self.data.url():"/firefox/data/";g.lib_path=g.lib_path||g.data_path+"src/lib";g.toJSON=function(){var a={},b;for(b in g)"function"!==typeof g[b]&&(a[b]=g[b]);return a};return g});
define("helpers/functional",[],function(){var b=Array.prototype.filter,g=Array.prototype.forEach,h=Function.prototype.bind,a=Array.prototype.slice,f=Object.prototype.toString,k=function(){},j={},l={changes:function(a,d){var e={new_values:{},old_values:{}},c;for(c in a)a[c]!==d[c]&&(e.new_values[c]=a[c],"undefined"!==typeof d[c]&&(e.old_values[c]=d[c]));for(c in d)e.new_values[c]||d[c]!==a[c]&&"undefined"!==typeof d[c]&&(e.old_values[c]=d[c]);return e},bind:function(b,d){var e,c;if(b.bind===h&&h)return h.apply(b,
a.call(arguments,1));if(!l.isFunction(b))throw new TypeError;c=a.call(arguments,2);return e=function(){if(!(this instanceof e))return b.apply(d,c.concat(a.call(arguments)));k.prototype=b.prototype;var i=new k,m=b.apply(i,c.concat(a.call(arguments)));return Object(m)===m?m:i}},delay:function(a,d){var e=Array.prototype.slice.call(arguments,2);return setTimeout(function(){return a.apply(null,e)},d)},debounce:function(a,d,e){var c,i;return function(){var m=this,b=arguments,g=e&&!c;clearTimeout(c);c=setTimeout(function(){c=
null;e||(i=a.apply(m,b))},d);g&&(i=a.apply(m,b));return i}},throttle:function(a,d){var e,c,i,m,b,g,f=l.debounce(function(){b=m=!1},d);return function(){e=this;c=arguments;i||(i=setTimeout(function(){i=null;b&&(g=a.apply(e,c));f()},d));m?b=!0:(m=!0,g=a.apply(e,c));f();return g}},each:function(a,d,e){if(g&&a.forEach===g)a.forEach(d,e);else if(a.length===+a.length)for(var c=0,i=a.length;c<i&&d.call(e,a[c],c,a)!==j;c++);else for(c in a)if(this.has(a,c)&&d.call(e,a[c],c,a)===j)break},filter:function(a,
d,e){var c=[];if(b&&a.filter===b)return a.filter(d,e);this.each(a,function(a,m,b){d.call(e,a,m,b)&&(c[c.length]=a)});return c},has:function(a,d){return a.hasOwnProperty(d)},clone:function(a){return"undefined"===typeof a?void 0:JSON.parse(JSON.stringify(a))},extend:function(a,d){for(var e in d)a[e]=d[e];return a},makeArray:function(a){return a=Array.isArray(a)?a:[a]}};l.each("Arguments Function String Number Date RegExp".split(" "),function(a){l["is"+a]=function(d){return f.call(d)=="[object "+a+"]"}});
return l});define("events",[],function(){return{LISTEN:"rt:lis",CONNECT:"rt:cct",DISCONNECT:"rt:dct",LOAD_STORAGE_INSTANCE:"st:ld",STORAGE_INSTANCE_DATA:"st:d",STORAGE_INSTANCE_SAVE:"st:sv",STORAGE_INSTANCE_CHANGE:"st:ch",STORAGE_INSTANCE_REMOVE:"st:rm",STORAGE_INSTANCE_CLEAR:"st:cl",MAKE_REQUEST:"rq:mk",REQUEST_COMPLETE:"rq:d",ABORT_REQUEST:"rq:x",RESIZE:"rsz",POPUP_SET:"pp:st",SUBSCRIBE:"sub",PUBLISH:"pub",UNSUBSCRIBE:"usb",LOAD_TABS:"tb:ld",INJECT:"tb:i",OPEN:"tb:o",OPEN_EXT_TAB:"etb:o"}});
define("router",["require","helpers/functional","events"],function(b){var g=b("helpers/functional"),h=b("events"),a={},f={},k={},j={},l={},n=function(c,a){k[a]||(k[a]={});k[a][c]=!0},d=function(c,a){if(l[c]){var d,e;d=l[c].worker;e=l[c].fn;if("local"===e){if(j[c]&&j[c][a.key]&&j[c][a.key].length){d=j[c][a.key];for(var b=0;b<d.length;b++)e=d[b],e(a)}}else e.apply(this,[d,a])}},e=function(c){c.target||(c.target="ext");if("*"===c.target&&k[c.key])for(var a in k[c.key])d(a,c);else{a=g.makeArray(c.target);
for(var e=0;e<a.length;e++){var b=a[e];k[c.key]&&k[c.key][b]&&d(b,c)}}},c=function(c,a,d){if("function"!==typeof d)throw"message listener for key ("+a+") callback must be a function";j[c]||(j[c]={});j[c][a]||(j[c][a]=[]);j[c][a].push(d)};g.extend(a,{init:function(c){a.set_options(c);a.connect("core",null,"local");a.on(h.LISTEN,function(c){n(c.worker,c.data)})},observer:null,set_observer:function(c){a.observer=c},on:function(a,d){if("string"===typeof a)n("core",a),c("core",a,d);else if(Array.isArray(a))a.forEach(function(a){n("core",
a.key);c("core",a.key,a.fn)});else if("object"===typeof a)for(var e in a){var b=e,g=a[e];n("core",b);c("core",b,g)}},set_options:function(c){c&&g.extend(f,c)},send:function(c,a,d){var b={worker:"core"};"object"===typeof c?g.extend(b,c):g.extend(b,{key:a,data:d,target:c});e(b)},connect:function(c,d,e){l[c]={worker:d,fn:e};a.observer&&a.observer.trigger("connect",c)},is_connected:function(c){return!!l[c]},disconnect:function(c){l[c]&&(delete l[c],a.observer&&a.observer.trigger("disconnect",c))},route:e});
a.init();return a});
(function(b){"function"===typeof bootstrap?bootstrap("promise",b):"function"===typeof define?define("q",b):"object"===typeof exports?module.exports=b():"undefined"!==typeof ses?ses.ok()&&(ses.makeQ=b):Q=b()})(function(){function b(c){var a=Function.call;return function(){return a.apply(c,arguments)}}function g(c,a){a.stack&&("object"===typeof c&&null!==c&&c.stack&&-1===c.stack.indexOf(I))&&(c.stack=h(c.stack)+"\n"+I+"\n"+h(a.stack))}function h(c){for(var c=c.split("\n"),a=[],d=0;d<c.length;++d){var e=
c[d],i;if(i=/at .+ \((.*):(\d+):\d+\)/.exec(e)){var b=i[2];i=i[1]===J&&b>=z&&b<=R}else i=!1;!i&&!(-1!==e.indexOf("(module.js:")||-1!==e.indexOf("(node.js:"))&&a.push(e)}return a.join("\n")}function a(){if(Error.captureStackTrace){var c,a,d=Error.prepareStackTrace;Error.prepareStackTrace=function(d,e){c=e[1].getFileName();a=e[1].getLineNumber()};Error().stack;Error.prepareStackTrace=d;J=c;return a}}function f(c){return s(c)}function k(){function c(i){a&&(e=s(i),A(a,function(c,a){u(function(){e.promiseDispatch.apply(e,
a)})},void 0),d=a=void 0)}var a=[],d=[],e,b=E(k.prototype),g=E(j.prototype);g.promiseDispatch=function(c,i,b){var g=t(arguments);a?(a.push(g),"when"===i&&b[1]&&d.push(b[1])):u(function(){e.promiseDispatch.apply(e,g)})};g.valueOf=function(){return a?g:e=l(e)};Error.captureStackTrace&&0<f.longStackJumpLimit&&(Error.captureStackTrace(g,k),g.stack=g.stack.substring(g.stack.indexOf("\n")+1));b.promise=g;b.resolve=c;b.fulfill=function(a){c(m(a))};b.reject=function(a){c(i(a))};b.notify=function(c){a&&A(d,
function(a,d){u(function(){d(c)})},void 0)};return b}function j(c,a,d,e){void 0===a&&(a=function(c){return i(Error("Promise does not support operation: "+c))});var b=E(j.prototype);b.promiseDispatch=function(d,e,g){var m;try{m=c[e]?c[e].apply(b,g):a.call(b,e,g)}catch(f){m=i(f)}d&&d(m)};d&&(b.valueOf=d);e&&(b.exception=e);return b}function l(c){return n(c)?c.valueOf():c}function n(c){return c&&"function"===typeof c.promiseDispatch}function d(c){return c&&"function"===typeof c.then}function e(c){return!d(l(c))}
function c(c){c=l(c);return n(c)&&"exception"in c}function i(c){var a=j({when:function(a){if(a){var d=S(F,this);-1!==d&&(B.splice(d,1),F.splice(d,1))}return a?a(c):this}},function(){return i(c)},function(){return this},c);!K&&("undefined"!==typeof window&&!window.Touch&&window.console)&&console.log("Should be empty:",B);K=!0;F.push(a);B.push(c);return a}function m(c){return j({when:function(){return c},get:function(a){return c[a]},set:function(a,d){c[a]=d},"delete":function(a){delete c[a]},post:function(a,
d){return null==a?c.apply(void 0,d):c[a].apply(c,d)},apply:function(a){return c.apply(void 0,a)},keys:function(){return T(c)}},void 0,function(){return c})}function s(c){if(n(c))return c;c=l(c);if(d(c)){var a=k();c.then(a.resolve,a.reject,a.notify);return a.promise}return m(c)}function p(c,a,d,e){function b(c){try{return"function"===typeof a?a(c):c}catch(d){return i(d)}}function m(c){if("function"===typeof d){g(c,j);try{return d(c)}catch(a){return i(a)}}return i(c)}var h=k(),n=!1,j=s(c);u(function(){j.promiseDispatch(function(c){n||
(n=!0,h.resolve(b(c)))},"when",[function(c){n||(n=!0,h.resolve(m(c)))}])});j.promiseDispatch(void 0,"when",[void 0,function(c){var a,d=!1;try{a="function"===typeof e?e(c):c}catch(i){if(d=!0,f.onerror)f.onerror(i);else throw i;}d||h.notify(a)}]);return h.promise}function x(c,a,d){return p(c,function(c){return y(c).then(function(c){return a.apply(void 0,c)},d)},d)}function v(c,a,d){var e=k();u(function(){s(c).promiseDispatch(e.resolve,a,d)});return e.promise}function q(c){return function(a){var d=t(arguments,
1);return v(a,c,d)}}function r(c,a){var d=t(arguments,2);return G(c,a,d)}function w(c){var a=t(arguments,1);return C(c,a)}function y(c){return p(c,function(c){var a=c.length;if(0===a)return s(c);var d=k();A(c,function(i,b,g){e(b)?(c[g]=l(b),0===--a&&d.resolve(c)):p(b,function(e){c[g]=e;0===--a&&d.resolve(c)}).fail(d.reject)},void 0);return d.promise})}function L(c,a){return p(c,void 0,a)}var z=a(),J,M=function(){},u;if("undefined"!==typeof process)u=process.nextTick;else if("function"===typeof setImmediate)u=
setImmediate;else if("undefined"!==typeof MessageChannel){var N=new MessageChannel,D={},O=D;N.port1.onmessage=function(){D=D.next;var c=D.task;delete D.task;c()};u=function(c){O=O.next={task:c};N.port2.postMessage(0)}}else u=function(c){setTimeout(c,0)};var t=b(Array.prototype.slice),A=b(Array.prototype.reduce||function(c,a){var d=0,e=this.length;if(1===arguments.length){do{if(d in this){a=this[d++];break}if(++d>=e)throw new TypeError;}while(1)}for(;d<e;d++)d in this&&(a=c(a,this[d],d));return a}),
S=b(Array.prototype.indexOf||function(c){for(var a=0;a<this.length;a++)if(this[a]===c)return a;return-1}),P=b(Array.prototype.map||function(c,a){var d=this,e=[];A(d,function(i,b,g){e.push(c.call(a,b,g,d))},void 0);return e}),E=Object.create||function(c){function a(){}a.prototype=c;return new a},T=Object.keys||function(c){var a=[],d;for(d in c)a.push(d);return a},U=b(Object.prototype.toString),H;H="undefined"!==typeof ReturnValue?ReturnValue:function(c){this.value=c};f.longStackJumpLimit=1;var I="From previous event:";
f.nextTick=u;f.defer=k;k.prototype.makeNodeResolver=function(){var c=this;return function(a,d){a?c.reject(a):2<arguments.length?c.resolve(t(arguments,1)):c.resolve(d)}};f.promise=function(c){var a=k();w(c,a.resolve,a.reject,a.notify).fail(a.reject);return a.promise};f.makePromise=j;j.prototype.then=function(c,a,d){return p(this,c,a,d)};j.prototype.thenResolve=function(c){return p(this,function(){return c})};A("isFulfilled isRejected isPending dispatch when spread get put set del delete post send invoke keys fapply fcall fbind all allResolved timeout delay catch finally fail fin progress done nfcall nfapply nfbind ncall napply nbind npost nsend ninvoke nodeify".split(" "),
function(c,a){j.prototype[a]=function(){return f[a].apply(f,[this].concat(t(arguments)))}},void 0);j.prototype.toSource=function(){return this.toString()};j.prototype.toString=function(){return"[object Promise]"};f.nearer=l;f.isPromise=n;f.isPromiseAlike=d;f.isPending=function(a){return!e(a)&&!c(a)};f.isFulfilled=e;f.isRejected=c;var F=[],B=[],K;if("undefined"!==typeof process&&process.on)process.on("exit",function(){for(var c=0;c<B.length;c++){var a=B[c];a&&"undefined"!==typeof a.stack?console.warn("Unhandled rejected promise:",
a.stack):console.warn("Unhandled rejected promise (no stack):",a)}});f.reject=i;f.fulfill=m;f.resolve=s;f.master=function(c){return j({isDef:function(){}},function(a,d){return v(c,a,d)},function(){return l(c)})};f.when=p;f.spread=x;f.async=function(c){return function(){function a(c,g){var m;try{m=d[c](g)}catch(f){return"[object StopIteration]"===U(f)||f instanceof H?f.value:i(f)}return p(m,e,b)}var d=c.apply(this,arguments),e=a.bind(a,"send"),b=a.bind(a,"throw");return e()}};f["return"]=function(c){throw new H(c);
};f.promised=function(c){return function(){return x([this,y(arguments)],function(a,d){return c.apply(a,d)})}};f.dispatch=v;f.dispatcher=q;f.get=q("get");f.set=q("set");f["delete"]=f.del=q("delete");var G=f.post=q("post");f.send=r;f.invoke=r;var C=f.fapply=q("apply");f["try"]=w;f.fcall=w;f.fbind=function(c){var a=t(arguments,1);return function(){var d=a.concat(t(arguments));return C(c,d)}};f.keys=q("keys");f.all=y;f.allResolved=function(c){return p(c,function(c){c=P(c,s);return p(y(P(c,function(c){return p(c,
M,M)})),function(){return c})})};f["catch"]=f.fail=L;f.progress=function(c,a){return p(c,void 0,void 0,a)};f["finally"]=f.fin=function(c,a){return p(c,function(c){return p(a(),function(){return c})},function(c){return p(a(),function(){return i(c)})})};f.done=function(c,a,d,e){var i=function(a){u(function(){g(a,c);if(f.onerror)f.onerror(a);else throw a;})},a=a||d||e?p(c,a,d,e):c;"object"===typeof process&&(process&&process.domain)&&(i=process.domain.bind(i));L(a,i)};f.timeout=function(c,a){var d=k(),
e=setTimeout(function(){d.reject(Error("Timed out after "+a+" ms"))},a);p(c,function(c){clearTimeout(e);d.resolve(c)},function(c){clearTimeout(e);d.reject(c)});return d.promise};f.delay=function(c,a){void 0===a&&(a=c,c=void 0);var d=k();setTimeout(function(){d.resolve(c)},a);return d.promise};f.nfapply=function(c,a){var d=t(a),e=k();d.push(e.makeNodeResolver());C(c,d).fail(e.reject);return e.promise};f.nfcall=function(c){var a=t(arguments,1),d=k();a.push(d.makeNodeResolver());C(c,a).fail(d.reject);
return d.promise};f.nfbind=function(c){var a=t(arguments,1);return function(){var d=a.concat(t(arguments)),e=k();d.push(e.makeNodeResolver());C(c,d).fail(e.reject);return e.promise}};f.npost=function(c,a,d){var d=t(d),e=k();d.push(e.makeNodeResolver());G(c,a,d).fail(e.reject);return e.promise};f.nsend=function(c,a){var d=t(arguments,2),e=k();d.push(e.makeNodeResolver());G(c,a,d).fail(e.reject);return e.promise};f.ninvoke=f.nsend;f.nodeify=function(c,a){if(a)c.then(function(c){u(function(){a(null,
c)})},function(c){u(function(){a(c)})});else return c};var R=a();return f});
define("helpers/string",[],function(){var b={capitalize:function(b){return this.capitalizePrototype.call(b)},capitalizePrototype:function(){return 0===this.length?this:this[0].toUpperCase()+this.slice(1)},trim:function(b,h){return this.trimPrototype.call(b,h)},trimPrototype:function(b){void 0===b&&(b="\\s");return this.replace(RegExp("(^["+b+"]*|["+b+"]*$)","g"),"")},generateGuid:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var h=16*Math.random()|0;return("x"==
b?h:h&3|8).toString(16)})},isEmail:function(b){return/[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])/i.test(b)},utf8:{encode:function(b){for(var b=b.replace(/\r\n/g,"\n"),h="",a=0;a<b.length;a++){var f=b.charCodeAt(a);128>f?h+=String.fromCharCode(f):(127<f&&2048>f?h+=String.fromCharCode(f>>6|192):(h+=String.fromCharCode(f>>12|224),h+=String.fromCharCode(f>>6&63|128)),h+=String.fromCharCode(f&63|128))}return h},
decode:function(b){for(var h="",a=0,f=0,k=0;a<b.length;)f=b.charCodeAt(a),128>f?(h+=String.fromCharCode(f),a++):191<f&&224>f?(k=b.charCodeAt(a+1),h+=String.fromCharCode((f&31)<<6|k&63),a+=2):(k=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),h+=String.fromCharCode((f&15)<<12|(k&63)<<6|c3&63),a+=3);return h},toByteArray:function(b){for(var h=[],a=0;a<b.length;a++)if(127>=b.charCodeAt(a))h.push(b.charCodeAt(a));else for(var f=encodeURIComponent(b.charAt(a)).substr(1).split("%"),k=0;k<f.length;k++)h.push(parseInt(f[k],
16));return h},parse:function(b){for(var h="",a=0;a<b.length;a++)h+=127>=b[a]?37===b[a]?"%25":String.fromCharCode(b[a]):"%"+b[a].toString(16).toUpperCase();return decodeURIComponent(h)}},get_html_translation_table:function(b,h){var a={},f={},k,j={},l={},n={},d={};j[0]="HTML_SPECIALCHARS";j[1]="HTML_ENTITIES";l[0]="ENT_NOQUOTES";l[2]="ENT_COMPAT";l[3]="ENT_QUOTES";n=!isNaN(b)?j[b]:b?b.toUpperCase():"HTML_SPECIALCHARS";d=!isNaN(h)?l[h]:h?h.toUpperCase():"ENT_COMPAT";if("HTML_SPECIALCHARS"!==n&&"HTML_ENTITIES"!==
n)throw Error("Table: "+n+" not supported");a["38"]="&amp;";"HTML_ENTITIES"===n&&(a["160"]="&nbsp;",a["161"]="&iexcl;",a["162"]="&cent;",a["163"]="&pound;",a["164"]="&curren;",a["165"]="&yen;",a["166"]="&brvbar;",a["167"]="&sect;",a["168"]="&uml;",a["169"]="&copy;",a["170"]="&ordf;",a["171"]="&laquo;",a["172"]="&not;",a["173"]="&shy;",a["174"]="&reg;",a["175"]="&macr;",a["176"]="&deg;",a["177"]="&plusmn;",a["178"]="&sup2;",a["179"]="&sup3;",a["180"]="&acute;",a["181"]="&micro;",a["182"]="&para;",
a["183"]="&middot;",a["184"]="&cedil;",a["185"]="&sup1;",a["186"]="&ordm;",a["187"]="&raquo;",a["188"]="&frac14;",a["189"]="&frac12;",a["190"]="&frac34;",a["191"]="&iquest;",a["192"]="&Agrave;",a["193"]="&Aacute;",a["194"]="&Acirc;",a["195"]="&Atilde;",a["196"]="&Auml;",a["197"]="&Aring;",a["198"]="&AElig;",a["199"]="&Ccedil;",a["200"]="&Egrave;",a["201"]="&Eacute;",a["202"]="&Ecirc;",a["203"]="&Euml;",a["204"]="&Igrave;",a["205"]="&Iacute;",a["206"]="&Icirc;",a["207"]="&Iuml;",a["208"]="&ETH;",a["209"]=
"&Ntilde;",a["210"]="&Ograve;",a["211"]="&Oacute;",a["212"]="&Ocirc;",a["213"]="&Otilde;",a["214"]="&Ouml;",a["215"]="&times;",a["216"]="&Oslash;",a["217"]="&Ugrave;",a["218"]="&Uacute;",a["219"]="&Ucirc;",a["220"]="&Uuml;",a["221"]="&Yacute;",a["222"]="&THORN;",a["223"]="&szlig;",a["224"]="&agrave;",a["225"]="&aacute;",a["226"]="&acirc;",a["227"]="&atilde;",a["228"]="&auml;",a["229"]="&aring;",a["230"]="&aelig;",a["231"]="&ccedil;",a["232"]="&egrave;",a["233"]="&eacute;",a["234"]="&ecirc;",a["235"]=
"&euml;",a["236"]="&igrave;",a["237"]="&iacute;",a["238"]="&icirc;",a["239"]="&iuml;",a["240"]="&eth;",a["241"]="&ntilde;",a["242"]="&ograve;",a["243"]="&oacute;",a["244"]="&ocirc;",a["245"]="&otilde;",a["246"]="&ouml;",a["247"]="&divide;",a["248"]="&oslash;",a["249"]="&ugrave;",a["250"]="&uacute;",a["251"]="&ucirc;",a["252"]="&uuml;",a["253"]="&yacute;",a["254"]="&thorn;",a["255"]="&yuml;");"ENT_NOQUOTES"!==d&&(a["34"]="&quot;");"ENT_QUOTES"===d&&(a["39"]="&#39;");a["60"]="&lt;";a["62"]="&gt;";for(k in a)a.hasOwnProperty(k)&&
(f[String.fromCharCode(k)]=a[k]);return f},html_entity_decode:function(g,h){var a={},f="",k="",j="",k=g.toString();if(!1===(a=b.get_html_translation_table("HTML_ENTITIES",h)))return!1;delete a["&"];a["&"]="&amp;";for(f in a)j=a[f],k=k.split(j).join(f);return k=k.split("&#039;").join("'")}};String.prototype.capitalize=b.capitalizePrototype;String.prototype.trim=b.trimPrototype;String.prototype.strip=b.trimPrototype;return b});
(function(b){function g(a){a=parseInt(a,10);if(NaN===a)throw Error("ValueError");return a}function h(a,e,c){var b=a.indexOf(":",e),m=g(a.slice(e,b));if("0"==a[e]&&b!=e+1)throw Error("ValueError");b++;a=a.slice(b,b+m);return[c&&c.utf8?k.decode(a):a,b+m]}function a(a){return"number"==typeof a&&a.toString()==parseInt(a.toString(),10)?"integer":"[object Array]"===Object.prototype.toString.call(a)?"array":typeof a}function f(a){return 1==a.length?"0"+a:a}b.utf8={};b.utf8.toByteArray=function(a){for(var e=
[],c=0;c<a.length;c++)if(127>=a.charCodeAt(c))e.push(a.charCodeAt(c));else for(var b=encodeURIComponent(a.charAt(c)).substr(1).split("%"),m=0;m<b.length;m++)e.push(parseInt(b[m],16));return e};b.utf8.parse=function(a){for(var e="",c=0;c<a.length;c++)e+=127>=a[c]?37===a[c]?"%25":String.fromCharCode(a[c]):"%"+a[c].toString(16).toUpperCase();return decodeURIComponent(e)};b.reversedict=function(a){var e={},c;for(c in a)e[a[c]]=c;return e};for(var k={encode:function(a){for(var a=a.replace(/\r\n/g,"\n"),
e="",c=0;c<a.length;c++){var b=a.charCodeAt(c);128>b?e+=String.fromCharCode(b):(127<b&&2048>b?e+=String.fromCharCode(b>>6|192):(e+=String.fromCharCode(b>>12|224),e+=String.fromCharCode(b>>6&63|128)),e+=String.fromCharCode(b&63|128))}return e},decode:function(a){for(var e="",c=0,b=c1=c2=0;c<a.length;)b=a.charCodeAt(c),128>b?(e+=String.fromCharCode(b),c++):191<b&&224>b?(c2=a.charCodeAt(c+1),e+=String.fromCharCode((b&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),e+=String.fromCharCode((b&
15)<<12|(c2&63)<<6|c3&63),c+=3);return e}},j={l:function(a,b,c){var i,m=[];for(b++;"e"!=a[b];)b=j[a[b]](a,b,c),i=b[0],b=b[1],m.push(i);return[m,b+1]},d:function(a,b,c){var i,m={};for(b++;"e"!=a[b];)b=h(a,b,c),i=b[0],b=b[1],b=j[a[b]](a,b,c),m[i]=b[0],b=b[1];return[m,b+1]},i:function(a,b){b++;var c=a.indexOf("e",b),i=g(a.slice(b,c));if("-"==a[b]){if("0"==a[b+1])throw Error("ValueError");}else if("0"==a[b]&&c!=b+1)throw Error("ValueError");return[i,c+1]}},l=0;10>l;l++)j[l.toString()]=h;b.bdecode=function(a,
b){return j[a[0]](a,0,b)[0]};var n={integer:function(a,b){b.push(105);for(var c=a.toString(),i=0;i<c.length;i++)b.push(c[i].charCodeAt(0));b.push(101)},string:function(a,b,c,i,m){if(m&&m.utf8)c=utf8.toByteArray(a);else{c=[];for(i=0;i<a.length;i++)c.push(a.charCodeAt(i))}a=c.length.toString();for(i=0;i<a.length;i++)b.push(a[i].charCodeAt(0));b.push(58);for(i=0;i<c.length;i++)b.push(c[i])},array:function(b,e,c,i,m){e.push(108);for(var f=0;f<b.length;f++)n[a(b[f])](b[f],e,c,i,m);e.push(101)},object:function(b,
e,c,i,f){e.push(100);var g=[],h;for(h in b)g.push(h);g.sort();for(var k=0;k<g.length;k++){h=g[k];for(var j=utf8.toByteArray(h),l=j.length.toString(),r=0;r<l.length;r++)e.push(l[r].charCodeAt(0));e.push(58);for(r=0;r<j.length;r++)e.push(j[r]);c.push(h);i&&i(c,e);n[a(b[h])](b[h],e,c,i,f);c.pop()}e.push(101)}};b.bencode=function(b,e,c){var i=[];n[a(b)](b,i,[],e,c);return i};b.ab2str=function(a){assert(!1);return String.fromCharCode.apply(null,new Uint16Array(a))};b.ab2arr=function(a){for(var b=[],c=
0;c<a.length;c++)b.push(a[c]);return b};b.arr2str=function(a,b){for(var c="",i=a.length,f=void 0===b?0:b;f<i;f++)c+=String.fromCharCode(a[f]);return c};b.ab2hex=function(a){for(var b=[],c=a.byteLength|a.length,i=0;i<c;i++)b.push(f(a[i].toString(16)));return b.join("")};b.str2arr=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c));return b};b.intersect=function(a,b){return a[1]<b[0]||b[1]<a[0]?null:[Math.max(a[0],b[0]),Math.min(a[1],b[1])]};define("helpers/torrent",["require","helpers/string"],
function(a){var e=a("helpers/string");return{getFileSize:function(a,b){"number"!==typeof b&&(b=1);for(var d="b kb Mb Gb Tb Pb Eb".split(" "),e=d.length-1,f=1,a=a/1024;1E3<=a&&f<e;)a/=1024,f++;return a.toFixed(b)+d[f]},parseMagnetLink:function(a){var a=e.html_entity_decode(a).replace("magnet:?","").split("&"),b={trackers:[]};a.forEach(function(a){a=a.split("=");"xt"===a[0]?b.hash=a[1].replace("urn:btih:","").toUpperCase():"tr"===a[0]&&(b.tracker=decodeURIComponent(a[1]),b.trackers.push(b.tracker))});
return b},getScrapedAvailability:function(a){if(0===a.complete||0===a.downloaded)return 0;var b=a.complete+a.incomplete;0===b&&(b=1);return 65535*(0.077*a.complete+0.0274*a.downloaded+6.417*(a.incomplete/b))},calculateHealth:function(a){var b=0;65536<=a&&b++;131072<=a&&b++;262144<=a&&b++;524288<=a&&b++;return b},utf8:b.utf8,reversedict:b.reversedict,bdecode:b.bdecode,bencode:b.bencode,ab2str:b.ab2str,ab2arr:b.ab2arr,arr2str:b.arr2str,ab2hex:b.ab2hex,str2arr:b.str2arr,intersect:b.intersect}})})(this);
define("request","helpers/functional events config router helpers/string helpers/torrent q".split(" "),function(b,g){var h=require("q"),a=require("helpers/string"),f=require("helpers/torrent");require("config");var k=require("router"),j={},l=[],n=null,d=100,e={},c=function(a){a=a.data;j[a]&&j[a].xhr.abort()},i=function(a){var c=a.worker,d=a.data.id,e=a.data.opts,a=new h.defer;b.extend(e,{worker:c,id:d,dfd:a});l.push(function(){w(e).then(function(a){k.send(c,g.REQUEST_COMPLETE,{response:a,id:d})},
function(a){k.send(c,g.REQUEST_COMPLETE,{response:a,id:d},c)})});m()},m=function(){n||(n=setTimeout(function(){clearTimeout(n);n=null;l.length&&(l.shift()(),m())},d))},s=function(){var c=a.generateGuid();return j[c]?s():c},p=function(a){if(4===this.readyState){var c=j[a.id];c&&(clearTimeout(c.timer),200===this.status||0===this.status&&this.responseText.length?c.dfd.resolve({data:this.responseText,status:"success",statusText:this.statusText,statusCode:this.status}):c.dfd.reject({data:this.status,status:"error",
statusText:this.statusText,statusCode:this.status}),delete j[a.id])}},x=function(a){if(2===this.readyState&&200===this.status){var c=j[a.id],b;clearTimeout(c.timer);b={all:this.getAllResponseHeaders(),"content-type":this.getResponseHeader("Content-Type"),"content-disposition":this.getResponseHeader("Content-Disposition")};c.dfd.resolve({data:b,status:"success",statusText:this.statusText,statusCode:this.status});delete j[a.id];this.abort()}4===this.readyState&&200!==this.status&&(c=j[a.id],clearTimeout(c.timer),
c.dfd.reject({data:this.status,status:"error",statusText:this.statusText,statusCode:this.status}),delete j[a.id])},v=function(a){if(200===this.status){var c=f.arr2str(new Uint8Array(this.response)),b=j[a.id];clearTimeout(b.timer);b.dfd.resolve({data:c,status:"success",statusText:this.statusText,statusCode:this.status})}else b=j[a.id],clearTimeout(b.timer),b.dfd.reject({data:null,status:"error",statusText:this.statusText,statusCode:this.status});delete j[a.id]},q=function(a){var c=j[a.id];clearTimeout(c.timer);
c.dfd.reject({data:null,status:"error",statusText:this.statusText,statusCode:this.status});delete j[a.id]},r=function(a){var c=j[a.id];c&&(clearTimeout(c.timer),c.dfd.reject({data:null,status:"error",statusText:"abort",statusCode:this.status}),delete j[a.id])},w=function(a,c,d){"function"===typeof c&&"function"!==typeof a.success&&(a.success=c);"function"===typeof d&&"function"!==typeof a.error&&(a.error=d);var c=a.dfd||new h.defer,d=new XMLHttpRequest,e=a.type?a.type.toUpperCase():"GET",i=a.dataType||
"html",f=a.id||s(),g=a.timeout||1E4;a.success&&c.promise.done(a.success);a.error&&c.promise.fail(a.error);d.open(e,a.url,!0);d.onabort=b.bind(r,d,a);"binary"===i?(d.responseType="arraybuffer",d.onload=b.bind(v,d,a),d.onerror=b.bind(q,d,a)):"head"===i?(d.onreadystatechange=b.bind(x,d,a),d.setRequestHeader("Range","bytes=1-2")):(d.onreadystatechange=b.bind(p,d,a),d.setRequestHeader("Content-Type",i));d.send(null);setTimeout(function(){j[f]&&j[f].xhr.abort()},g);j[f]={xhr:d,dfd:c,opts:a};return c.promise};
b.extend(e,{init:function(a){a.spacing&&(d=a.spacing);k.on(g.MAKE_REQUEST,i);k.on(g.ABORT_REQUEST,c)},request:function(a){var c=new h.defer,d=a.id||s();b.extend(a,{dfd:c,id:d});l.push(function(){w(a)});m();return c.promise}});return e});define("storage",[],function(){var b=chrome.storage.local,g=chrome.storage.sync;return{local:b,sync:g,clear:function(){b.clear();g.clear()}}});
define("observer","require helpers/functional events router underscore config".split(" "),function(b){b("helpers/functional");var g=b("events"),h=b("router");b("config");var a=b("underscore"),b={},f={},k=function(a){return f[a]||new j(a)},j=function(a){this.name=a;this.listeners={};if(f[a])throw"Observer with name '"+a+"' already exists.";f[a]=this};j.prototype={subscribe:function(a,b){this.listeners[a]||(this.listeners[a]={});this.listeners[a][b]||(this.listeners[a][b]="core"===b?[]:!0)},unsubscribe:function(a,
b){this.listeners[a]&&delete this.listeners[a][b]},trigger:function(b){var d=this.listeners[b];if(d&&!a.isEmpty(d))for(var e in d){var c=a.toArray(arguments);"core"===e?(c.shift(),a.each(this.listeners[b].core,function(a){a.fn.apply(a.ctx,c)})):(c.unshift(this.name),h.send(e,g.PUBLISH,c))}return this},on:function(a,b,e){this.subscribe(a,"core");this.listeners[a].core.push({fn:b,ctx:e||this});return this},off:function(b,d){var e=!1;d&&a.isFunction(d)?(this.listeners[b].core&&a.each(this.listeners[b].core,
function(a,b,e){if(d===a.fn)return e.splice(b,1),!1}),this.listeners[b].core.length||(e=!0)):e=!0;e&&this.unsubscribe(b,"core");return this}};var l=k("router");h.set_observer(l);h.on(g.SUBSCRIBE,function(a){var b=a.data.event,e=a.data.name,a=a.worker,c=f[e];!c&&!b?new j(e):c&&b&&c.subscribe(b,a)});h.on(g.UNSUBSCRIBE,function(a){var b=a.data.event,e=a.worker;(a=f[a.data.name])&&a.unsubscribe(b,e)});h.on(g.PUBLISH,function(a){var a=a.data,b=a.shift();(b=f[b])&&b.trigger.apply(b,a)});a.extend(b,{load:k});
return b});
define("extension_storage","require underscore helpers/functional events storage observer router".split(" "),function(b){var g=b("helpers/functional"),h=b("events"),a=b("router");b("observer");var f=b("underscore"),k=b("storage"),j={},l={},b={},n=function(a,b,f){f||(f="core");d(a)?a=d(a):(j[a]=new e(a,b),a=j[a]);a.register(f);return a},d=function(a){return a?j[a]:j},e=function(a,b){b||(b={});this.KEY=a;this.loaded=!1;this.opts=g.extend({storage:"local",wait:0,defaults:{}},b);if(!("local"!==this.opts.storage&&
"sync"!==this.opts.storage)){var d=this,e={},f=[],h=!1;g.extend(e,{add:function(a,c,b){f.push({fn:a,arg:c,cb:b});e.process()},process:function(){if(!h&&f.length){h=!0;var a=f.shift();d.storage[a.fn](a.arg,function(){a.cb&&"function"===typeof a.cb&&a.cb.apply(d,arguments);h=!1;e.process()})}}});this.queue=e;this.storage=k[this.opts.storage];this.set_defaults();this.opts.wait&&(this.save_persistent=g.throttle(g.bind(this.save_persistent,this),this.opts.wait));this.load()}};e.prototype={load:function(){var a=
this;this.queue.add("get",this.KEY,function(b){this.loaded=!0;b&&b[a.KEY]&&g.extend(a.data,b[a.KEY]);a.trigger("reset",a.data)})},set_defaults:function(){this.data=g.clone(this.opts.defaults)},set:function(a,b){if("object"===typeof a)for(var d in a)this.set(d,a[d]);else this.data[a]=b;return this},get:function(a){return a?this.data[a]:this.data},remove:function(a){a&&(delete this.data[a],this.save());return this},clear:function(){this.queue.add("remove",this.KEY,function(){this.set_defaults();this.save()});
return this},save:function(a){var b={};a&&"object"===typeof a&&this.set(a);b[this.KEY]=this.data;this.save_persistent(b);return this},save_persistent:function(a){var b=this,d={},e;this.queue.add("get",this.KEY,function(f){f&&f[b.KEY]&&(d=f[b.KEY]);b.queue.add("set",a);e=g.changes(a[b.KEY],d);b.trigger("change",e)})},register:function(a){l[this.KEY]||(l[this.KEY]={});l[this.KEY][a]={};return this},unregister:function(a){delete l[this.KEY][a];return this},on:function(a,b,d){if(!l[this.KEY][d])throw"Trying to listen to storage instance event in core for unregistered target: "+
a+", "+d;l[this.KEY][d][a]||(l[this.KEY][d][a]=[]);l[this.KEY][d][a].push(b)},off:function(){},trigger:function(a,b){var d=l[this.KEY],e;for(e in d)if(d[e][a])for(var f=d[e][a],g=0,h=f.length;g<h;g++)f[g].call(this,b)}};a.on(h.LOAD_STORAGE_INSTANCE,function(c){var b;b=n(c.data.key,c.data.opts,c.worker);if(b.loaded){var d=b.get();b.queue.add("get",b.KEY,function(e){e&&e[b.KEY]&&g.extend(d,e[b.KEY]);a.send(c.worker,h.STORAGE_INSTANCE_DATA,{key:b.KEY,data:d})})}b.on("reset",function(b){a.send(c.worker,
h.STORAGE_INSTANCE_DATA,{key:this.KEY,data:b})},c.worker);b.on("change",function(b){a.send(c.worker,h.STORAGE_INSTANCE_CHANGE,{key:this.KEY,changes:b})},c.worker)});a.on(h.STORAGE_INSTANCE_SAVE,function(a){var b=a.data.key,a=a.data.data,e=d(b);if(!e)throw"Can't Save Unknown Storage Instance: "+b;e.save(a)});a.on(h.STORAGE_INSTANCE_REMOVE,function(a){var b=a.data.key,a=a.data.data,e=d(b);if(!e)throw"Can't Remove From Unknown Storage Instance: "+b;e.remove(a)});a.on(h.STORAGE_INSTANCE_CLEAR,function(a){a=
d(a.data.key);if(!a)throw"Can't Clear Unknown Storage Instance";a.clear()});a.observer.on("disconnect",function(a){f.each(j,function(b){b.unregister(a)})});g.extend(b,{load:n,get:d});return b});define("load_fn",["config"],function(){var b=require("config");return function(g,h){var a=b.data_path+h+"/"+g+"/"+g+".html";this[g]=document.createElement("iframe");this[g].src=a;this[g].name=g;document.body.appendChild(this[g])}});
define("popup","require helpers/functional events router observer underscore config".split(" "),function(b){var g=b("helpers/functional"),h=b("underscore"),a=b("events"),f=b("router"),k=b("observer"),j=b("config"),l={},n=function(a){var c=a.data.v,a=l["set_"+a.data.k];h.isFunction(a)&&a(c)},d=function(a){a=j.data_path+a;chrome.browserAction.setIcon({path:a})},e=function(a){chrome.browserAction.setTitle({title:a})},c=function(a){"popup"===a.name&&(f.connect(a.name,a,function(a,c){a.postMessage(c)}),
a.onMessage.addListener(function(a){f.route(a)}),a.onDisconnect.addListener(function(){f.disconnect(a.name);i.trigger("close")}),i.trigger("open"))},i=k.load("popup");g.extend(l,{init:function(b){var g;g=b.icons?"app/"+b.icons.popup_default:"lib/img/popup_default.png";chrome.browserAction.setPopup({popup:"popup/chrome/popup.chrome.html"});d(g);b.meta.fullName&&e(b.meta.fullName);chrome.extension.onConnect.addListener(c);f.on(a.POPUP_SET,n)},set_icon:d,set_title:e});return l});
define("tabs","require events router observer underscore config".split(" "),function(b){var g=b("underscore"),h=b("events"),a=b("router"),f=b("observer");b("config");var b={},k={},j=null,l=f.load("tabs"),n=function(a){return new e(a)},d=function(a,b,d){b?chrome.tabs.query({currentWindow:!0,active:!0},function(b){chrome.tabs.update(b.id,{url:a})}):chrome.tabs.create({url:a,active:!!d})},e=function(a){this.tab=a;this.id=this.tab.id;k[this.id]=this;l.trigger("create",this.to_JSON())};e.prototype={inject:function(a,
b){chrome.tabs.executeScript(this.id,{code:this.wrap_script(a,b),runAt:"document_end"})},wrap_script:function(a,b){return["(function(){","var Port = chrome.extension.connect({name:'"+("tab_"+this.id+"_"+b)+"'});","var Message = {send:function(key,pload){Port.postMessage({key:key,data:pload});}};",a,"})();"].join("")},to_JSON:function(){return{id:this.id,title:this.get_title(),url:this.get_url(),favicon:this.get_favicon()}},removed:function(){this.cleanup()},updated:function(a){this.tab=a;l.trigger("update",
this.to_JSON());"complete"===this.tab.status&&l.trigger("ready",this.id)},activated:function(){j=this;l.trigger("active",this.id)},on_ready:function(){l.trigger("ready",this.id)},get_url:function(){return this.tab.url},get_title:function(){return this.tab.title},get_favicon:function(){return this.tab.favIconUrl},cleanup:function(){l.trigger("remove",this.to_JSON());j===this&&(j=null);delete k[this.id]}};chrome.tabs.query({},function(a){g.each(a,n)});chrome.tabs.onCreated.addListener(n);chrome.tabs.onRemoved.addListener(function(a){(a=
k[a])&&a.removed()});chrome.tabs.onUpdated.addListener(function(a,b,d){(a=k[a])&&a.updated(d)});chrome.tabs.onActivated.addListener(function(a){(a=k[a.tabId])&&a.activated()});chrome.extension.onConnect.addListener(function(c){if(0===c.name.indexOf("tab_")){var b=c.name.split("_")[2];a.connect(c.name,c,function(a,c){a.postMessage(c)});c.onMessage.addListener(function(d){a.route({worker:c.name,target:b,key:d.key,data:d.data})});c.onDisconnect.addListener(function(){a.disconnect(c.name)})}});a.on(h.LOAD_TABS,
function(c){var b=[];g.each(k,function(a){b.push(a.to_JSON())});a.send(c.worker,h.LOAD_TABS,b)});a.on(h.INJECT,function(a){var b=a.worker,d=a.data.src;(a=k[a.data.id])&&a.inject(d,b)});a.on(h.OPEN,function(a){d.apply(this,a.data)});g.extend(b,{open:d});return b});
define("extension_tabs","require events router observer underscore tabs config".split(" "),function(b){var g=b("underscore"),h=b("events"),a=b("router");b("observer");var f=b("tabs");b("config");var k=null,b={},j=function(b){0===b.name.indexOf("ext_")&&(a.connect(b.name,b,function(a,c){a.postMessage(c)}),b.onMessage.addListener(function(b){a.route(b)}),b.onDisconnect.addListener(function(){a.disconnect(b.name)}))},l=function(a){n.call(this,a.data)},n=function(a){if(a.name)if(k&&(k.tabs&&k.tabs[a.name]||
k.popup===a.name))a="tabs/chrome/tab.chrome.html?"+btoa(JSON.stringify(a)),f.open(a,!1,!0);else throw"extension tab not in manifest.  will not open";};g.extend(b,{init:function(b){k=b;chrome.extension.onConnect.addListener(j);a.on(h.OPEN_EXT_TAB,l)},open:n});return b});
define("loader","helpers/functional config q underscore request extension_storage load_fn popup observer extension_tabs".split(" "),function(b){var g=require("config"),h=require("extension_storage"),a=require("q"),f=require("underscore"),k=require("request"),j=require("popup"),l=require("load_fn"),n=require("observer"),d=require("extension_tabs"),e={},c={},i,m,s=!1,p=function(a,b,d){l.apply(c,[a,b?"app":"core",d])},x=function(c,d,e){var g=a.defer(),h=null,i=[];k.request({url:c+d,dataType:"html"}).then(function(d){try{h=
JSON.parse(d.data)}catch(k){g.resolve(null);return}h.sources={};h.styles={};h.cscripts={};e&&(c+=h.meta.version+"/");var j,l=h,m=c,n=a.defer(),p=[],z={},d=function(a,c){if(a){var b=q(m,c,l.meta.version);b.then(function(a){z[c]=a});p.push(b)}};for(j in l.workers)d(l.workers[j],j);a.all(p).then(function(){n.resolve(z)},function(){n.reject(z)});j=n.promise;j.then(function(a){b.extend(h.sources,a)},function(){});i.push(j);h.popup&&(j=v(h,c,"js"),d=v(h,c,"css"),j.then(function(a){b.extend(h.sources,{popup:a})},
function(){}),d.then(function(a){b.extend(h.styles,{popup:a})},function(){}),i.push(j),i.push(d));h.tabs&&f.each(h.tabs,function(a,b){var d=q(c,b,h.meta.version,"js"),e=q(c,b,h.meta.version,"css");d.then(function(a){h.sources[b]=a},function(){});e.then(function(a){h.styles[b]=a},function(){});i.push(d);i.push(e)});h.content_scripts&&f.each(h.content_scripts,function(a,b){var d=q(c,b,h.meta.version,"js");d.then(function(a){h.cscripts[b]=a},function(){});i.push(d)});a.all(i).then(function(){g.resolve(h)},
function(){g.reject(null)})},function(){g.resolve(h)});return g.promise},v=function(b,c,d){var e=a.defer();q(c,b.popup,b.meta.version,d).then(function(a){e.resolve(a)},function(){e.reject(null)});return e.promise},q=function(b,c,d,e){var e=e||"js",f=a.defer();k.request({url:b+"app/"+c+"/"+c+"."+e+"?v="+d,dataType:"html"}).then(function(a){f.resolve(a.data)},function(a){f.reject(a.statusCode)});return f.promise},r=function(){var b=a.defer(),c=i.get("manifest"),d,e,h,j=x(g.app.remote_src[g.env],"latest.manifest.json",
!0),k=x(g.data_path,"app/bt.manifest.json",!1);j.then(function(a){e=a});k.then(function(a){d=a.meta.version;h=a});a.all([j,k]).then(function(){var a,j;f.each({local:h,cached:c},function(b,c){if(b&&(!a||b.meta&&b.meta.version>a.meta.version))if(d>=b.meta.version_min||"local"===c)a=b,j=c});if(a&&j)g.source=j,i.set("manifest",a).save(),b.resolve(a);else throw"Something went horribly wrong.  Couldn't load any form of bt.manifest.json";});return b.promise},w=function(a){var b;a.popup&&j.init(a,
e);for(b in a.workers)p(b,a.workers[b],a.plugin_worker===b);a.tabs&&d.init(a,e)},y=function(){s||(s=!0,r().then(w))};b.extend(e,{load_manifest:r,load:p,get:function(a){return a?c[a]:c},set:function(a,b){c[a]=b},remove:function(a){delete c[a]},init:function(){m=n.load("loader");m.on("config:get",function(){var a=g.toJSON();a._install=_install;m.trigger("config:got",a)});i=h.load("sources");i.on("reset",y,"core")}});return e});
define("message",["helpers/functional","events","router","loader"],function(b,g){var h=require("router"),a=require("loader"),f={};h.on(g.CONNECT,function(b){"popup"===b.worker||0===b.worker.indexOf("ext_")||h.connect(b.worker,a.get(b.worker).contentWindow,function(a,b){a.postMessage(b,"*")})});window.addEventListener("message",function(a){h.route(a.data)},!1);b.extend(f,{});return f});
define("clipboard",["underscore","observer"],function(){var b=require("observer");require("underscore");var g=null,g=b.load("clipboard");g.on("copy",function(b){var a=document.createElement("textarea");a.value=b;document.body.appendChild(a);a.focus();a.select();document.execCommand("Copy");document.body.removeChild(a);g.trigger("copied",b)});return{}});
define("browser","require config router message loader request tabs extension_storage observer clipboard".split(" "),function(b){b("config");b("message");var g=b("router"),h=b("loader"),a=b("request");b("tabs");var f=b("extension_storage");b("clipboard");var k=function(){return{router:g,request:a,loader:h,extension_storage:f}},j=!1,l=[],n=function(){for(;l.length;)l.shift()(k())};a.init({spacing:100});h.init({});j=!0;n();return{ready:function(a){l.push(a);j&&n()},get_core:k}});
