define("main",["require","plugin_install.require.config"],function(a,b){global_require.config(b);var e,d,f,c,g={"plugin:install_plugin":"step_1",download:"step_2","false":"step_3"},i=function(a){if(a=g[a])d("#progress").removeClass(function(){return d(this).attr("class")}).addClass(a),"step_3"===a&&c.trigger("show")};return{init:function(){a(["underscore","jquery","handlebars","plugin_templates"],function(){a("underscore");d=a("jquery");f=_sandbox.observer.load("app");c=_sandbox.observer.load("popup");
var g=window.location.href.split("?")[1];e=JSON.parse(atob(g)).plugin;e.filename=e.download_url.split("/");e.filename=e.filename[e.filename.length-1];d("body").append(Handlebars.templates.main(e));f.on("state",i);d(".download").click(function(){i("download")});f.trigger("get_state")})}}});define("app/plugin_install",function(){});
var Handlebars={VERSION:"1.0.beta.6",helpers:{},partials:{},registerHelper:function(a,b,e){e&&(b.not=e);this.helpers[a]=b},registerPartial:function(a,b){this.partials[a]=b}};Handlebars.registerHelper("helperMissing",function(a){if(2!==arguments.length)throw Error("Could not find property '"+a+"'");});var toString=Object.prototype.toString,functionType="[object Function]";
Handlebars.registerHelper("blockHelperMissing",function(a,b){var e=b.inverse||function(){},d=b.fn,f="",c=toString.call(a);c===functionType&&(a=a.call(this));if(!0===a)return d(this);if(!1===a||null==a)return e(this);if("[object Array]"===c){if(0<a.length){e=0;for(c=a.length;e<c;e++)f+=d(a[e])}else f=e(this);return f}return d(a)});Handlebars.registerHelper("each",function(a,b){var e=b.fn,d=b.inverse,f="";if(a&&0<a.length)for(var d=0,c=a.length;d<c;d++)f+=e(a[d]);else f=d(this);return f});
Handlebars.registerHelper("if",function(a,b){toString.call(a)===functionType&&(a=a.call(this));return!a||Handlebars.Utils.isEmpty(a)?b.inverse(this):b.fn(this)});Handlebars.registerHelper("unless",function(a,b){var e=b.fn;b.fn=b.inverse;b.inverse=e;return Handlebars.helpers["if"].call(this,a,b)});Handlebars.registerHelper("with",function(a,b){return b.fn(a)});Handlebars.registerHelper("log",function(a){Handlebars.log(a)});
var handlebars=function(){return{trace:function(){},yy:{},symbols_:{error:2,root:3,program:4,EOF:5,statements:6,simpleInverse:7,statement:8,openInverse:9,closeBlock:10,openBlock:11,mustache:12,partial:13,CONTENT:14,COMMENT:15,OPEN_BLOCK:16,inMustache:17,CLOSE:18,OPEN_INVERSE:19,OPEN_ENDBLOCK:20,path:21,OPEN:22,OPEN_UNESCAPED:23,OPEN_PARTIAL:24,params:25,hash:26,param:27,STRING:28,INTEGER:29,BOOLEAN:30,hashSegments:31,hashSegment:32,ID:33,EQUALS:34,pathSegments:35,SEP:36,$accept:0,$end:1},terminals_:{2:"error",
5:"EOF",14:"CONTENT",15:"COMMENT",16:"OPEN_BLOCK",18:"CLOSE",19:"OPEN_INVERSE",20:"OPEN_ENDBLOCK",22:"OPEN",23:"OPEN_UNESCAPED",24:"OPEN_PARTIAL",28:"STRING",29:"INTEGER",30:"BOOLEAN",33:"ID",34:"EQUALS",36:"SEP"},productions_:[0,[3,2],[4,3],[4,1],[4,0],[6,1],[6,2],[8,3],[8,3],[8,1],[8,1],[8,1],[8,1],[11,3],[9,3],[10,3],[12,3],[12,3],[13,3],[13,4],[7,2],[17,3],[17,2],[17,2],[17,1],[25,2],[25,1],[27,1],[27,1],[27,1],[27,1],[26,1],[31,2],[31,1],[32,3],[32,3],[32,3],[32,3],[21,1],[35,3],[35,1]],performAction:function(a,
b,e,d,f,c){a=c.length-1;switch(f){case 1:return c[a-1];case 2:this.$=new d.ProgramNode(c[a-2],c[a]);break;case 3:this.$=new d.ProgramNode(c[a]);break;case 4:this.$=new d.ProgramNode([]);break;case 5:this.$=[c[a]];break;case 6:c[a-1].push(c[a]);this.$=c[a-1];break;case 7:this.$=new d.InverseNode(c[a-2],c[a-1],c[a]);break;case 8:this.$=new d.BlockNode(c[a-2],c[a-1],c[a]);break;case 9:this.$=c[a];break;case 10:this.$=c[a];break;case 11:this.$=new d.ContentNode(c[a]);break;case 12:this.$=new d.CommentNode(c[a]);
break;case 13:this.$=new d.MustacheNode(c[a-1][0],c[a-1][1]);break;case 14:this.$=new d.MustacheNode(c[a-1][0],c[a-1][1]);break;case 15:this.$=c[a-1];break;case 16:this.$=new d.MustacheNode(c[a-1][0],c[a-1][1]);break;case 17:this.$=new d.MustacheNode(c[a-1][0],c[a-1][1],!0);break;case 18:this.$=new d.PartialNode(c[a-1]);break;case 19:this.$=new d.PartialNode(c[a-2],c[a-1]);break;case 21:this.$=[[c[a-2]].concat(c[a-1]),c[a]];break;case 22:this.$=[[c[a-1]].concat(c[a]),null];break;case 23:this.$=[[c[a-
1]],c[a]];break;case 24:this.$=[[c[a]],null];break;case 25:c[a-1].push(c[a]);this.$=c[a-1];break;case 26:this.$=[c[a]];break;case 27:this.$=c[a];break;case 28:this.$=new d.StringNode(c[a]);break;case 29:this.$=new d.IntegerNode(c[a]);break;case 30:this.$=new d.BooleanNode(c[a]);break;case 31:this.$=new d.HashNode(c[a]);break;case 32:c[a-1].push(c[a]);this.$=c[a-1];break;case 33:this.$=[c[a]];break;case 34:this.$=[c[a-2],c[a]];break;case 35:this.$=[c[a-2],new d.StringNode(c[a])];break;case 36:this.$=
[c[a-2],new d.IntegerNode(c[a])];break;case 37:this.$=[c[a-2],new d.BooleanNode(c[a])];break;case 38:this.$=new d.IdNode(c[a]);break;case 39:c[a-2].push(c[a]);this.$=c[a-2];break;case 40:this.$=[c[a]]}},table:[{3:1,4:2,5:[2,4],6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],22:[1,13],23:[1,14],24:[1,15]},{1:[3]},{5:[1,16]},{5:[2,3],7:17,8:18,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,19],20:[2,3],22:[1,13],23:[1,14],24:[1,15]},{5:[2,5],14:[2,5],15:[2,5],16:[2,5],19:[2,
5],20:[2,5],22:[2,5],23:[2,5],24:[2,5]},{4:20,6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],20:[2,4],22:[1,13],23:[1,14],24:[1,15]},{4:21,6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],20:[2,4],22:[1,13],23:[1,14],24:[1,15]},{5:[2,9],14:[2,9],15:[2,9],16:[2,9],19:[2,9],20:[2,9],22:[2,9],23:[2,9],24:[2,9]},{5:[2,10],14:[2,10],15:[2,10],16:[2,10],19:[2,10],20:[2,10],22:[2,10],23:[2,10],24:[2,10]},{5:[2,11],14:[2,11],15:[2,11],16:[2,11],19:[2,11],20:[2,11],22:[2,
11],23:[2,11],24:[2,11]},{5:[2,12],14:[2,12],15:[2,12],16:[2,12],19:[2,12],20:[2,12],22:[2,12],23:[2,12],24:[2,12]},{17:22,21:23,33:[1,25],35:24},{17:26,21:23,33:[1,25],35:24},{17:27,21:23,33:[1,25],35:24},{17:28,21:23,33:[1,25],35:24},{21:29,33:[1,25],35:24},{1:[2,1]},{6:30,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],22:[1,13],23:[1,14],24:[1,15]},{5:[2,6],14:[2,6],15:[2,6],16:[2,6],19:[2,6],20:[2,6],22:[2,6],23:[2,6],24:[2,6]},{17:22,18:[1,31],21:23,33:[1,25],35:24},{10:32,20:[1,
33]},{10:34,20:[1,33]},{18:[1,35]},{18:[2,24],21:40,25:36,26:37,27:38,28:[1,41],29:[1,42],30:[1,43],31:39,32:44,33:[1,45],35:24},{18:[2,38],28:[2,38],29:[2,38],30:[2,38],33:[2,38],36:[1,46]},{18:[2,40],28:[2,40],29:[2,40],30:[2,40],33:[2,40],36:[2,40]},{18:[1,47]},{18:[1,48]},{18:[1,49]},{18:[1,50],21:51,33:[1,25],35:24},{5:[2,2],8:18,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],20:[2,2],22:[1,13],23:[1,14],24:[1,15]},{14:[2,20],15:[2,20],16:[2,20],19:[2,20],22:[2,20],23:[2,20],24:[2,
20]},{5:[2,7],14:[2,7],15:[2,7],16:[2,7],19:[2,7],20:[2,7],22:[2,7],23:[2,7],24:[2,7]},{21:52,33:[1,25],35:24},{5:[2,8],14:[2,8],15:[2,8],16:[2,8],19:[2,8],20:[2,8],22:[2,8],23:[2,8],24:[2,8]},{14:[2,14],15:[2,14],16:[2,14],19:[2,14],20:[2,14],22:[2,14],23:[2,14],24:[2,14]},{18:[2,22],21:40,26:53,27:54,28:[1,41],29:[1,42],30:[1,43],31:39,32:44,33:[1,45],35:24},{18:[2,23]},{18:[2,26],28:[2,26],29:[2,26],30:[2,26],33:[2,26]},{18:[2,31],32:55,33:[1,56]},{18:[2,27],28:[2,27],29:[2,27],30:[2,27],33:[2,
27]},{18:[2,28],28:[2,28],29:[2,28],30:[2,28],33:[2,28]},{18:[2,29],28:[2,29],29:[2,29],30:[2,29],33:[2,29]},{18:[2,30],28:[2,30],29:[2,30],30:[2,30],33:[2,30]},{18:[2,33],33:[2,33]},{18:[2,40],28:[2,40],29:[2,40],30:[2,40],33:[2,40],34:[1,57],36:[2,40]},{33:[1,58]},{14:[2,13],15:[2,13],16:[2,13],19:[2,13],20:[2,13],22:[2,13],23:[2,13],24:[2,13]},{5:[2,16],14:[2,16],15:[2,16],16:[2,16],19:[2,16],20:[2,16],22:[2,16],23:[2,16],24:[2,16]},{5:[2,17],14:[2,17],15:[2,17],16:[2,17],19:[2,17],20:[2,17],22:[2,
17],23:[2,17],24:[2,17]},{5:[2,18],14:[2,18],15:[2,18],16:[2,18],19:[2,18],20:[2,18],22:[2,18],23:[2,18],24:[2,18]},{18:[1,59]},{18:[1,60]},{18:[2,21]},{18:[2,25],28:[2,25],29:[2,25],30:[2,25],33:[2,25]},{18:[2,32],33:[2,32]},{34:[1,57]},{21:61,28:[1,62],29:[1,63],30:[1,64],33:[1,25],35:24},{18:[2,39],28:[2,39],29:[2,39],30:[2,39],33:[2,39],36:[2,39]},{5:[2,19],14:[2,19],15:[2,19],16:[2,19],19:[2,19],20:[2,19],22:[2,19],23:[2,19],24:[2,19]},{5:[2,15],14:[2,15],15:[2,15],16:[2,15],19:[2,15],20:[2,
15],22:[2,15],23:[2,15],24:[2,15]},{18:[2,34],33:[2,34]},{18:[2,35],33:[2,35]},{18:[2,36],33:[2,36]},{18:[2,37],33:[2,37]}],defaultActions:{16:[2,1],37:[2,23],53:[2,21]},parseError:function(a){throw Error(a);},parse:function(a){var b=[0],e=[null],d=[],f=this.table,c="",g=0,i=0,p=0;this.lexer.setInput(a);this.lexer.yy=this.yy;this.yy.lexer=this.lexer;"undefined"==typeof this.lexer.yylloc&&(this.lexer.yylloc={});a=this.lexer.yylloc;d.push(a);"function"===typeof this.yy.parseError&&(this.parseError=
this.yy.parseError);for(var j,q,m,h,l={},n,k;;){m=b[b.length-1];this.defaultActions[m]?h=this.defaultActions[m]:(null==j&&(j=void 0,j=this.lexer.lex()||1,"number"!==typeof j&&(j=this.symbols_[j]||j)),h=f[m]&&f[m][j]);if(("undefined"===typeof h||!h.length||!h[0])&&!p){k=[];for(n in f[m])this.terminals_[n]&&2<n&&k.push("'"+this.terminals_[n]+"'");var r="",r=this.lexer.showPosition?"Parse error on line "+(g+1)+":\n"+this.lexer.showPosition()+"\nExpecting "+k.join(", ")+", got '"+this.terminals_[j]+"'":
"Parse error on line "+(g+1)+": Unexpected "+(1==j?"end of input":"'"+(this.terminals_[j]||j)+"'");this.parseError(r,{text:this.lexer.match,token:this.terminals_[j]||j,line:this.lexer.yylineno,loc:a,expected:k})}if(h[0]instanceof Array&&1<h.length)throw Error("Parse Error: multiple actions possible at state: "+m+", token: "+j);switch(h[0]){case 1:b.push(j);e.push(this.lexer.yytext);d.push(this.lexer.yylloc);b.push(h[1]);j=null;q?(j=q,q=null):(i=this.lexer.yyleng,c=this.lexer.yytext,g=this.lexer.yylineno,
a=this.lexer.yylloc,0<p&&p--);break;case 2:k=this.productions_[h[1]][1];l.$=e[e.length-k];l._$={first_line:d[d.length-(k||1)].first_line,last_line:d[d.length-1].last_line,first_column:d[d.length-(k||1)].first_column,last_column:d[d.length-1].last_column};m=this.performAction.call(l,c,i,g,this.yy,h[1],e,d);if("undefined"!==typeof m)return m;k&&(b=b.slice(0,-2*k),e=e.slice(0,-1*k),d=d.slice(0,-1*k));b.push(this.productions_[h[1]][0]);e.push(l.$);d.push(l._$);h=f[b[b.length-2]][b[b.length-1]];b.push(h);
break;case 3:return!0}}return!0},lexer:{EOF:1,parseError:function(a,b){if(this.yy.parseError)this.yy.parseError(a,b);else throw Error(a);},setInput:function(a){this._input=a;this._more=this._less=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.match+=a;this.matched+=a;a.match(/\n/)&&
this.yylineno++;this._input=this._input.slice(1);return a},unput:function(a){this._input=a+this._input;return this},more:function(){this._more=!0;return this},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),
b=Array(a.length+1).join("-");return a+this.upcomingInput()+"\n"+b+"^"},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,b;this._more||(this.match=this.yytext="");for(var e=this._currentRules(),d=0;d<e.length;d++)if(a=this._input.match(this.rules[e[d]])){if(b=a[0].match(/\n.*/g))this.yylineno+=b.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:b?b[b.length-1].length-1:this.yylloc.last_column+
a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];if(a=this.performAction.call(this,this.yy,this,e[d],this.conditionStack[this.conditionStack.length-1]))return a;return}if(""===this._input)return this.EOF;this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();
return"undefined"!==typeof a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},popState:function(){return this.conditionStack.pop()},_currentRules:function(){return this.conditions[this.conditionStack[this.conditionStack.length-1]].rules},topState:function(){return this.conditionStack[this.conditionStack.length-2]},pushState:function(a){this.begin(a)},performAction:function(a,b,e){switch(e){case 0:"\\"!==b.yytext.slice(-1)&&this.begin("mu");"\\"===b.yytext.slice(-1)&&(b.yytext=b.yytext.substr(0,
b.yyleng-1),this.begin("emu"));if(b.yytext)return 14;break;case 1:return 14;case 2:return this.popState(),14;case 3:return 24;case 4:return 16;case 5:return 20;case 6:return 19;case 7:return 19;case 8:return 23;case 9:return 23;case 10:return b.yytext=b.yytext.substr(3,b.yyleng-5),this.popState(),15;case 11:return 22;case 12:return 34;case 13:return 33;case 14:return 33;case 15:return 36;case 17:return this.popState(),18;case 18:return this.popState(),18;case 19:return b.yytext=b.yytext.substr(1,
b.yyleng-2).replace(/\\"/g,'"'),28;case 20:return 30;case 21:return 30;case 22:return 29;case 23:return 33;case 24:return b.yytext=b.yytext.substr(1,b.yyleng-2),33;case 25:return"INVALID";case 26:return 5}},rules:[/^[^\x00]*?(?=(\{\{))/,/^[^\x00]+/,/^[^\x00]{2,}?(?=(\{\{))/,/^\{\{>/,/^\{\{#/,/^\{\{\//,/^\{\{\^/,/^\{\{\s*else\b/,/^\{\{\{/,/^\{\{&/,/^\{\{![\s\S]*?\}\}/,/^\{\{/,/^=/,/^\.(?=[} ])/,/^\.\./,/^[\/.]/,/^\s+/,/^\}\}\}/,/^\}\}/,/^"(\\["]|[^"])*"/,/^true(?=[}\s])/,/^false(?=[}\s])/,/^[0-9]+(?=[}\s])/,
/^[a-zA-Z0-9_$-]+(?=[=}\s\/.])/,/^\[[^\]]*\]/,/^./,/^$/],conditions:{mu:{rules:[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],inclusive:!1},emu:{rules:[2],inclusive:!1},INITIAL:{rules:[0,1,26],inclusive:!0}}}}}();
"undefined"!==typeof require&&"undefined"!==typeof exports&&(exports.parser=handlebars,exports.parse=function(){return handlebars.parse.apply(handlebars,arguments)},exports.main=function(a){if(!a[1])throw Error("Usage: "+a[0]+" FILE");a="undefined"!==typeof process?require("fs").readFileSync(require("path").join(process.cwd(),a[1]),"utf8"):require("file").path(require("file").cwd()).join(a[1]).read({charset:"utf-8"});return exports.parser.parse(a)},"undefined"!==typeof module&&require.main===module&&
exports.main("undefined"!==typeof process?process.argv.slice(1):require("system").args));Handlebars.Parser=handlebars;Handlebars.parse=function(a){Handlebars.Parser.yy=Handlebars.AST;return Handlebars.Parser.parse(a)};Handlebars.print=function(a){return(new Handlebars.PrintVisitor).accept(a)};Handlebars.logger={DEBUG:0,INFO:1,WARN:2,ERROR:3,level:3,log:function(){}};Handlebars.log=function(a,b){Handlebars.logger.log(a,b)};
(function(){Handlebars.AST={};Handlebars.AST.ProgramNode=function(a,e){this.type="program";this.statements=a;e&&(this.inverse=new Handlebars.AST.ProgramNode(e))};Handlebars.AST.MustacheNode=function(a,e,d){this.type="mustache";this.id=a[0];this.params=a.slice(1);this.hash=e;this.escaped=!d};Handlebars.AST.PartialNode=function(a,e){this.type="partial";this.id=a;this.context=e};var a=function(a,e){if(a.original!==e.original)throw new Handlebars.Exception(a.original+" doesn't match "+e.original);};Handlebars.AST.BlockNode=
function(b,e,d){a(b.id,d);this.type="block";this.mustache=b;this.program=e};Handlebars.AST.InverseNode=function(b,e,d){a(b.id,d);this.type="inverse";this.mustache=b;this.program=e};Handlebars.AST.ContentNode=function(a){this.type="content";this.string=a};Handlebars.AST.HashNode=function(a){this.type="hash";this.pairs=a};Handlebars.AST.IdNode=function(a){this.type="ID";this.original=a.join(".");for(var e=[],d=0,f=0,c=a.length;f<c;f++){var g=a[f];".."===g?d++:"."===g||"this"===g?this.isScoped=!0:e.push(g)}this.parts=
e;this.string=e.join(".");this.depth=d;this.isSimple=1===e.length&&0===d};Handlebars.AST.StringNode=function(a){this.type="STRING";this.string=a};Handlebars.AST.IntegerNode=function(a){this.type="INTEGER";this.integer=a};Handlebars.AST.BooleanNode=function(a){this.type="BOOLEAN";this.bool=a};Handlebars.AST.CommentNode=function(a){this.type="comment";this.comment=a}})();
Handlebars.Exception=function(a){var b=Error.prototype.constructor.apply(this,arguments),e;for(e in b)b.hasOwnProperty(e)&&(this[e]=b[e]);this.message=b.message};Handlebars.Exception.prototype=Error();Handlebars.SafeString=function(a){this.string=a};Handlebars.SafeString.prototype.toString=function(){return this.string.toString()};
(function(){var a={"<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},b=/&(?!\w+;)|[<>"'`]/g,e=/[&<>"'`]/,d=function(b){return a[b]||"&amp;"};Handlebars.Utils={escapeExpression:function(a){return a instanceof Handlebars.SafeString?a.toString():null==a||!1===a?"":!e.test(a)?a:a.replace(b,d)},isEmpty:function(a){return"undefined"===typeof a?!0:null===a?!0:!1===a?!0:"[object Array]"===Object.prototype.toString.call(a)&&0===a.length?!0:!1}}})();Handlebars.Compiler=function(){};
Handlebars.JavaScriptCompiler=function(){};
(function(a,b){a.OPCODE_MAP={appendContent:1,getContext:2,lookupWithHelpers:3,lookup:4,append:5,invokeMustache:6,appendEscaped:7,pushString:8,truthyOrFallback:9,functionOrFallback:10,invokeProgram:11,invokePartial:12,push:13,assignToHash:15,pushStringParam:16};a.MULTI_PARAM_OPCODES={appendContent:1,getContext:1,lookupWithHelpers:2,lookup:1,invokeMustache:3,pushString:1,truthyOrFallback:1,functionOrFallback:1,invokeProgram:3,invokePartial:1,push:1,assignToHash:1,pushStringParam:1};a.DISASSEMBLE_MAP=
{};for(var e in a.OPCODE_MAP)a.DISASSEMBLE_MAP[a.OPCODE_MAP[e]]=e;a.multiParamSize=function(g){return a.MULTI_PARAM_OPCODES[a.DISASSEMBLE_MAP[g]]};a.prototype={compiler:a,disassemble:function(){for(var g=this.opcodes,i,b=[],c,d=0,e=g.length;d<e;d++)if(i=g[d],"DECLARE"===i)c=g[++d],i=g[++d],b.push("DECLARE "+c+" = "+i);else{c=a.DISASSEMBLE_MAP[i];for(var f=a.multiParamSize(i),l=[],n=0;n<f;n++)i=g[++d],"string"===typeof i&&(i='"'+i.replace("\n","\\n")+'"'),l.push(i);c=c+" "+l.join(" ");b.push(c)}return b.join("\n")},
guid:0,compile:function(a,i){this.children=[];this.depths={list:[]};this.options=i;var b=this.options.knownHelpers;this.options.knownHelpers={helperMissing:!0,blockHelperMissing:!0,each:!0,"if":!0,unless:!0,"with":!0,log:!0};if(b)for(var c in b)this.options.knownHelpers[c]=b[c];return this.program(a)},accept:function(a){return this[a.type](a)},program:function(a){var a=a.statements,b;this.opcodes=[];for(var c=0,d=a.length;c<d;c++)b=a[c],this[b.type](b);this.isSimple=1===d;this.depths.list=this.depths.list.sort(function(a,
g){return a-g});return this},compileProgram:function(a){var a=(new this.compiler).compile(a,this.options),b=this.guid++;this.usePartial=this.usePartial||a.usePartial;this.children[b]=a;for(var c=0,d=a.depths.list.length;c<d;c++)depth=a.depths.list[c],2>depth||this.addDepth(depth-1);return b},block:function(a){var b=a.mustache,c=this.setupStackForMustache(b),d=this.compileProgram(a.program);a.program.inverse&&(a=this.compileProgram(a.program.inverse),this.declare("inverse",a));this.opcode("invokeProgram",
d,c.length,!!b.hash);this.declare("inverse",null);this.opcode("append")},inverse:function(a){var b=this.setupStackForMustache(a.mustache),c=this.compileProgram(a.program);this.declare("inverse",c);this.opcode("invokeProgram",null,b.length,!!a.mustache.hash);this.declare("inverse",null);this.opcode("append")},hash:function(a){var a=a.pairs,b,c;this.opcode("push","{}");for(var d=0,e=a.length;d<e;d++)b=a[d],c=b[1],this.accept(c),this.opcode("assignToHash",b[0])},partial:function(a){var b=a.id;this.usePartial=
!0;a.context?this.ID(a.context):this.opcode("push","depth0");this.opcode("invokePartial",b.original);this.opcode("append")},content:function(a){this.opcode("appendContent",a.string)},mustache:function(a){var b=this.setupStackForMustache(a);this.opcode("invokeMustache",b.length,a.id.original,!!a.hash);a.escaped&&!this.options.noEscape?this.opcode("appendEscaped"):this.opcode("append")},ID:function(a){this.addDepth(a.depth);this.opcode("getContext",a.depth);this.opcode("lookupWithHelpers",a.parts[0]||
null,a.isScoped||!1);for(var b=1,c=a.parts.length;b<c;b++)this.opcode("lookup",a.parts[b])},STRING:function(a){this.opcode("pushString",a.string)},INTEGER:function(a){this.opcode("push",a.integer)},BOOLEAN:function(a){this.opcode("push",a.bool)},comment:function(){},pushParams:function(a){for(var b=a.length,c;b--;)if(c=a[b],this.options.stringParams)c.depth&&this.addDepth(c.depth),this.opcode("getContext",c.depth||0),this.opcode("pushStringParam",c.string);else this[c.type](c)},opcode:function(b,
c,d,e){this.opcodes.push(a.OPCODE_MAP[b]);void 0!==c&&this.opcodes.push(c);void 0!==d&&this.opcodes.push(d);void 0!==e&&this.opcodes.push(e)},declare:function(a,b){this.opcodes.push("DECLARE");this.opcodes.push(a);this.opcodes.push(b)},addDepth:function(a){0!==a&&!this.depths[a]&&(this.depths[a]=!0,this.depths.list.push(a))},setupStackForMustache:function(a){var b=a.params;this.pushParams(b);a.hash&&this.hash(a.hash);this.ID(a.id);return b}};b.prototype={nameLookup:function(a,c){return/^[0-9]+$/.test(c)?
a+"["+c+"]":b.isValidJavaScriptVariableName(c)?a+"."+c:a+"['"+c+"']"},appendToBuffer:function(a){return this.environment.isSimple?"return "+a+";":"buffer += "+a+";"},initializeBuffer:function(){return this.quotedString("")},namespace:"Handlebars",compile:function(a,b,d,e){this.environment=a;this.options=b||{};this.name=this.environment.name;this.isChild=!!d;this.context=d||{programs:[],aliases:{self:"this"},registers:{list:[]}};this.preamble();this.stackSlot=0;this.stackVars=[];this.compileChildren(a,
b);a=a.opcodes;this.i=0;for(c=a.length;this.i<c;this.i++)a=this.nextOpcode(0),"DECLARE"===a[0]?(this.i+=2,this[a[1]]=a[2]):(this.i+=a[1].length,this[a[0]].apply(this,a[1]));return this.createFunctionContext(e)},nextOpcode:function(b){var c=this.environment.opcodes,d=c[this.i+b],e,f;if("DECLARE"===d)return e=c[this.i+1],b=c[this.i+2],["DECLARE",e,b];e=a.DISASSEMBLE_MAP[d];d=a.multiParamSize(d);f=[];for(var m=0;m<d;m++)f.push(c[this.i+m+1+b]);return[e,f]},eat:function(a){this.i+=a.length},preamble:function(){var a=
[];this.useRegister("foundHelper");if(this.isChild)a.push("");else{var b=this.namespace,c="helpers = helpers || "+b+".helpers;";this.environment.usePartial&&(c=c+" partials = partials || "+b+".partials;");a.push(c)}this.environment.isSimple?a.push(""):a.push(", buffer = "+this.initializeBuffer());this.lastContext=0;this.source=a},createFunctionContext:function(a){var b=this.stackVars;this.isChild||(b=b.concat(this.context.registers.list));0<b.length&&(this.source[1]=this.source[1]+", "+b.join(", "));
if(!this.isChild)for(var c in this.context.aliases)this.source[1]=this.source[1]+", "+c+"="+this.context.aliases[c];this.source[1]&&(this.source[1]="var "+this.source[1].substring(2)+";");this.isChild||(this.source[1]+="\n"+this.context.programs.join("\n")+"\n");this.environment.isSimple||this.source.push("return buffer;");b=this.isChild?["depth0","data"]:["Handlebars","depth0","helpers","partials","data"];c=0;for(var d=this.environment.depths.list.length;c<d;c++)b.push("depth"+this.environment.depths.list[c]);
if(a)return b.push(this.source.join("\n  ")),Function.apply(this,b);a="function "+(this.name||"")+"("+b.join(",")+") {\n  "+this.source.join("\n  ")+"}";Handlebars.log(Handlebars.logger.DEBUG,a+"\n\n");return a},appendContent:function(a){this.source.push(this.appendToBuffer(this.quotedString(a)))},append:function(){var a=this.popStack();this.source.push("if("+a+" || "+a+" === 0) { "+this.appendToBuffer(a)+" }");this.environment.isSimple&&this.source.push("else { "+this.appendToBuffer("''")+" }")},
appendEscaped:function(){var a=this.nextOpcode(1),b="";this.context.aliases.escapeExpression="this.escapeExpression";"appendContent"===a[0]&&(b=" + "+this.quotedString(a[1][0]),this.eat(a));this.source.push(this.appendToBuffer("escapeExpression("+this.popStack()+")"+b))},getContext:function(a){this.lastContext!==a&&(this.lastContext=a)},lookupWithHelpers:function(a,b){if(a){var c=this.nextStack();this.usingKnownHelper=!1;!b&&this.options.knownHelpers[a]?(c=c+" = "+this.nameLookup("helpers",a,"helper"),
this.usingKnownHelper=!0):b||this.options.knownHelpersOnly?c=c+" = "+this.nameLookup("depth"+this.lastContext,a,"context"):(this.register("foundHelper",this.nameLookup("helpers",a,"helper")),c=c+" = foundHelper || "+this.nameLookup("depth"+this.lastContext,a,"context"));this.source.push(c+";")}else this.pushStack("depth"+this.lastContext)},lookup:function(a){var b=this.topStack();this.source.push(b+" = ("+b+" === null || "+b+" === undefined || "+b+" === false ? "+b+" : "+this.nameLookup(b,a,"context")+
");")},pushStringParam:function(a){this.pushStack("depth"+this.lastContext);this.pushString(a)},pushString:function(a){this.pushStack(this.quotedString(a))},push:function(a){this.pushStack(a)},invokeMustache:function(a,b,c){this.populateParams(a,this.quotedString(b),"{}",null,c,function(a,b,c){this.usingKnownHelper||(this.context.aliases.helperMissing="helpers.helperMissing",this.context.aliases.undef="void 0",this.source.push("else if("+c+"=== undef) { "+a+" = helperMissing.call("+b+"); }"),a!==
c&&this.source.push("else { "+a+" = "+c+"; }"))})},invokeProgram:function(a,b,c){var d=this.programExpression(this.inverse),a=this.programExpression(a);this.populateParams(b,null,a,d,c,function(a,b){this.usingKnownHelper||(this.context.aliases.blockHelperMissing="helpers.blockHelperMissing",this.source.push("else { "+a+" = blockHelperMissing.call("+b+"); }"))})},populateParams:function(a,b,c,d,e,f){var h=e||this.options.stringParams||d||this.options.data,l=this.popStack(),n=[],k;h?(this.register("tmp1",
c),k="tmp1"):k="{ hash: {} }";h&&(e=e?this.popStack():"{}",this.source.push("tmp1.hash = "+e+";"));this.options.stringParams&&this.source.push("tmp1.contexts = [];");for(h=0;h<a;h++)e=this.popStack(),n.push(e),this.options.stringParams&&this.source.push("tmp1.contexts.push("+this.popStack()+");");d&&(this.source.push("tmp1.fn = tmp1;"),this.source.push("tmp1.inverse = "+d+";"));this.options.data&&this.source.push("tmp1.data = data;");n.push(k);this.populateCall(n,l,b||l,f,"{}"!==c)},populateCall:function(a,
b,c,d,e){var f=["depth0"].concat(a).join(", "),a=["depth0"].concat(c).concat(a).join(", "),c=this.nextStack();this.usingKnownHelper?this.source.push(c+" = "+b+".call("+f+");"):(this.context.aliases.functionType='"function"',this.source.push("if("+(e?"foundHelper && ":"")+"typeof "+b+" === functionType) { "+c+" = "+b+".call("+f+"); }"));d.call(this,c,a,b);this.usingKnownHelper=!1},invokePartial:function(a){params=[this.nameLookup("partials",a,"partial"),"'"+a+"'",this.popStack(),"helpers","partials"];
this.options.data&&params.push("data");this.pushStack("self.invokePartial("+params.join(", ")+");")},assignToHash:function(a){var b=this.popStack(),c=this.topStack();this.source.push(c+"['"+a+"'] = "+b+";")},compiler:b,compileChildren:function(a,b){for(var c=a.children,d,e,f=0,h=c.length;f<h;f++){d=c[f];e=new this.compiler;this.context.programs.push("");var l=this.context.programs.length;d.index=l;d.name="program"+l;this.context.programs[l]=e.compile(d,b,this.context)}},programExpression:function(a){if(null==
a)return"self.noop";for(var b=this.environment.children[a],a=b.depths.list,b=[b.index,b.name,"data"],c=0,d=a.length;c<d;c++)depth=a[c],1===depth?b.push("depth0"):b.push("depth"+(depth-1));if(0===a.length)return"self.program("+b.join(", ")+")";b.shift();return"self.programWithDepth("+b.join(", ")+")"},register:function(a,b){this.useRegister(a);this.source.push(a+" = "+b+";")},useRegister:function(a){this.context.registers[a]||(this.context.registers[a]=!0,this.context.registers.list.push(a))},pushStack:function(a){this.source.push(this.nextStack()+
" = "+a+";");return"stack"+this.stackSlot},nextStack:function(){this.stackSlot++;this.stackSlot>this.stackVars.length&&this.stackVars.push("stack"+this.stackSlot);return"stack"+this.stackSlot},popStack:function(){return"stack"+this.stackSlot--},topStack:function(){return"stack"+this.stackSlot},quotedString:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r")+'"'}};e="break else new var case finally return void catch for switch while continue function this with default if throw delete in try do instanceof typeof abstract enum int short boolean export interface static byte extends long super char final native synchronized class float package throws const goto private transient debugger implements protected volatile double import public let yield".split(" ");
for(var d=b.RESERVED_WORDS={},f=0,c=e.length;f<c;f++)d[e[f]]=!0;b.isValidJavaScriptVariableName=function(a){return!b.RESERVED_WORDS[a]&&/^[a-zA-Z_$][0-9a-zA-Z_$]+$/.test(a)?!0:!1}})(Handlebars.Compiler,Handlebars.JavaScriptCompiler);Handlebars.precompile=function(a,b){var b=b||{},e=Handlebars.parse(a),e=(new Handlebars.Compiler).compile(e,b);return(new Handlebars.JavaScriptCompiler).compile(e,b)};
Handlebars.compile=function(a,b){var b=b||{},e;return function(d,f){if(!e){var c=Handlebars.parse(a),c=(new Handlebars.Compiler).compile(c,b),c=(new Handlebars.JavaScriptCompiler).compile(c,b,void 0,!0);e=Handlebars.template(c)}return e.call(this,d,f)}};
Handlebars.VM={template:function(a){var b={escapeExpression:Handlebars.Utils.escapeExpression,invokePartial:Handlebars.VM.invokePartial,programs:[],program:function(a,b,f){var c=this.programs[a];if(f)return Handlebars.VM.program(b,f);c||(c=this.programs[a]=Handlebars.VM.program(b));return c},programWithDepth:Handlebars.VM.programWithDepth,noop:Handlebars.VM.noop};return function(e,d){d=d||{};return a.call(b,Handlebars,e,d.helpers,d.partials,d.data)}},programWithDepth:function(a,b,e){var d=Array.prototype.slice.call(arguments,
2);return function(e,c){c=c||{};return a.apply(this,[e,c.data||b].concat(d))}},program:function(a,b){return function(e,d){d=d||{};return a(e,d.data||b)}},noop:function(){return""},invokePartial:function(a,b,e,d,f,c){options={helpers:d,partials:f,data:c};if(void 0===a)throw new Handlebars.Exception("The partial "+b+" could not be found");if(a instanceof Function)return a(e,options);if(Handlebars.compile)return f[b]=Handlebars.compile(a),f[b](e,options);throw new Handlebars.Exception("The partial "+
b+" could not be compiled when running in runtime-only mode");}};Handlebars.template=Handlebars.VM.template;define("handlebars",function(a){return function(){return a.Handlebars}}(this));
(function(){var a=Handlebars.template;(Handlebars.templates=Handlebars.templates||{}).main=a(function(a,e,d){var d=d||a.helpers,f,c=this.escapeExpression,a='<div id="progress">\n\t<section class="top">\n\t\t<header class="wrap">\n\t\t\t<div class="logo">\n\t\t\t\t<img src="../img/surf_banner.png" />\n\t\t\t</div>\n\t\t</header>\n\t\t<div class="wrap">\n\t\t\t<h1>Welcome to Surf Safari</h1>\n\t\t\t<div class="copy cf">\n\t\t\t\t<a class="download btn" href="';(f=d.download_url)?f=f.call(e,{hash:{}}):
(f=e.download_url,f="function"===typeof f?f():f);a+=c(f)+'">Download</a>\n\t\t\t\t<div class="p">Surf requires BitTorrent Torque to handle .torrent files. <br />Follow the steps below to complete the installatiopn process.</div>\n\t\t\t</div>\n\t\t</div>\n\t</section>\n\n\t<section class="mid">\n\t\t<div class="steps wrap cf">\n\t\t\t<div class="step_1">\n\t\t\t\t<img src="../img/gray_arrow.png" />\n\t\t\t\t<div class="copy">\n\t\t\t\t\tDownload the BitTorrent Torque installer provided above.\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<div class="step_2">\n\t\t\t\t<img src="../img/install_screens.png" />\n\t\t\t\t<div class="copy">\n\t\t\t\t\tRun the downloaded installer <em>';
(f=d.filename)?f=f.call(e,{hash:{}}):(f=e.filename,f="function"===typeof f?f():f);return a+=c(f)+'</em> from your downloads folder and follow the instructions in the install dialogs.\n\t\t\t\t</div>\t\t\t</div>\n\t\t\t<div class="step_3">\n\t\t\t\t<img src="../img/safari_screencap.png" />\n\t\t\t\t<div class="copy">\n\t\t\t\t\tInstallation Complete.<br /><br />\n\t\t\t\t\tClick on the Surf icon to the left of the omni-box to Surf in Safari!\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</section>\n</div>'})})();
define("plugin_templates",["handlebars"],function(){});
